baseURL = "https://jdavibedoya.github.io/"
languageCode = "en-us"
title = "David Bedoya | Audio & AI/ML Engineering"
theme = "PaperMod"
publishDir = "docs"

[params]
  defaultTheme = "auto"
  # description = "Audio & AI/ML Portfolio"
  
  [params.homeInfoParams]
    Title = "Welcome to my portfolio! 👋"
    Content = """
**Electronics Engineer & M.Sc. in Sound and Music Computing**. <br>
After a rewarding chapter as a university lecturer in music technology, I am transitioning into AI/ML engineering. I bring together academic rigor, problem-solving skills, and hands-on experience in Python, Deep Learning, and Signal Processing. I seek a team where I can contribute technically while continuing to learn and adapt to industry standards.
"""
    
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/jdavibedoya"
  
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/jdavibedoya"

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10

  [[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    url = "/teaching/"
    weight = 20

  [[menu.main]]
    identifier = "education"
    name = "Education"
    url = "/education/"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Forzando reconstrucción del sitio