baseURL = "https://jdavibedoya.github.io/"
languageCode = "en-us"
title = "David Bedoya | AI/ML & Audio Engineering"
theme = "PaperMod"
publishDir = "docs"

[params]
  defaultTheme = "auto"
  # description = "AI/ML & Audio Portfolio"
  
  [params.homeInfoParams]
    Title = "Welcome to my portfolio! 👋"
    Content = """A teacher by vocation with an endless curiosity for learning. I am an Electronic Engineer (UdeA) with a Master's in Sound and Music Computing (UPF). Beyond the classroom and technology, I find my balance playing the drums, running, and practicing yoga."""
    
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/jdavibedoya"
  
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/jdavibedoya"

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10

  [[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    url = "/teaching/"
    weight = 20

  [[menu.main]]
    identifier = "education"
    name = "Education"
    url = "/education/"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true